let discussions = [
  {
    id: "1",
    image: "images/user1.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "2",
    image: "images/user2.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "3",
    image: "images/user3.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "4",
    image: "images/user4.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "5",
    image: "images/user5.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit lorem ipsum dolor sit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "6",
    image: "images/user1.png",
    username: "anejohn",
    text: "Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "7",
    image: "images/user2.png",
    username: "anejohn",
    text: "Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "8",
    image: "images/user3.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "9",
    image: "images/user4.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "10",
    image: "images/user5.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "11",
    image: "images/user1.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "12",
    image: "images/user2.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "13",
    image: "images/user3.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "14",
    image: "images/user4.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit .Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore! Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
  {
    id: "15",
    image: "images/user5.png",
    username: "anejohn",
    text: "Lorem ipsum dolor sit amet consectetur adipisicing elit.Lorem ipsum dolor Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia laboriosam eveniet corporis a soluta tempore!",
    comments: "10",
    reactions: "84",
  },
];
